# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
email: subramanian.srikrishnan@hotmail.com
description: Perspectives
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://srikrishnansubramanian.github.io" # the base hostname & protocol for your site
twitter_username: srikrishnan_23
github_username:  srikrishnansubramanian
paginate: 5
youtube_username: https://www.youtube.com/channel/UCq-H8hQPEOpKwPsk61YWteQ

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
